global:
  scrape_interval: 15s     # Cada 15s pide métricas a Spring Boot
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'ws-chat'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets:
          - 'host.docker.internal:8080'  # Mac / Windows
          # - '172.17.0.1:8080'           # Linux (IP del bridge de Docker)
